#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/nremote/nremote /usr/bin/nremote

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/nremote.service ]; then
			rm /etc/systemd/system/nremote.service /usr/lib/systemd/system/nremote.service /usr/lib/systemd/user/nremote.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/nremote/files/systemd/nremote.service /usr/lib/systemd/system/nremote.service
		# try fix error in Ubuntu 18.04
		# Failed to reload nremote.service: Unit nremote.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/nremote.service:10: Executable path is not absolute: pkill -f "nremote --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/nremote.service
		fi
		systemctl daemon-reload
		systemctl enable nremote
		systemctl start nremote
	fi
fi
